/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DBWeather = IDL.Record({
  'cloudCover' : IDL.Opt(IDL.Float64),
  'temperatureMax' : IDL.Opt(IDL.Float64),
  'temperatureMin' : IDL.Opt(IDL.Float64),
  'country' : IDL.Text,
  'precipitation' : IDL.Opt(IDL.Float64),
  'temperature' : IDL.Opt(IDL.Float64),
  'city' : IDL.Text,
  'windSpeed' : IDL.Opt(IDL.Float64),
  'solar' : IDL.Opt(IDL.Float64),
  'windDirection' : IDL.Opt(IDL.Float64),
  'temperatureDaily' : IDL.Opt(IDL.Float64),
  'precipitationProbability' : IDL.Opt(IDL.Float64),
  'condition' : IDL.Text,
});
export const Precipitation = IDL.Record({
  'probability' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const WeeklyForecast = IDL.Record({
  'precipitation' : Precipitation,
  'temperature' : IDL.Opt(IDL.Float64),
  'windSpeed' : IDL.Float64,
  'timestamp' : IDL.Int,
  'windDir' : IDL.Float64,
  'condition' : IDL.Text,
});
export const WeatherResponse = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'daily' : IDL.Record({
    'precipitation' : Precipitation,
    'temperature' : IDL.Opt(IDL.Float64),
    'windSpeed' : IDL.Float64,
    'windDir' : IDL.Float64,
    'condition' : IDL.Text,
  }),
  'weekly' : IDL.Vec(WeeklyForecast),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'conditionForWeather' : IDL.Func([DBWeather], [IDL.Text], ['query']),
  'getBackendCachedRainViewer' : IDL.Func([], [IDL.Text], []),
  'getCachedWeather' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WeatherResponse)],
      ['query'],
    ),
  'getCurrentWeather' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(WeatherResponse)],
      ['query'],
    ),
  'getDailyForecast' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int],
      [IDL.Opt(WeeklyForecast)],
      ['query'],
    ),
  'getHealthCheck' : IDL.Func(
      [],
      [
        IDL.Record({
          'status' : IDL.Text,
          'version' : IDL.Text,
          'timestamp' : IDL.Int,
        }),
      ],
      ['query'],
    ),
  'getRainViewerCache' : IDL.Func([], [IDL.Text], []),
  'getWeather' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(WeatherResponse)],
      ['query'],
    ),
  'getWeatherData' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'country' : IDL.Text,
          'city' : IDL.Text,
          'daily' : IDL.Record({
            'precipitation' : IDL.Record({
              'probability' : IDL.Float64,
              'amount' : IDL.Float64,
            }),
            'temperature' : IDL.Opt(IDL.Float64),
            'windSpeed' : IDL.Float64,
            'windDir' : IDL.Float64,
            'condition' : IDL.Text,
          }),
          'weekly' : IDL.Vec(
            IDL.Record({
              'precipitation' : IDL.Record({
                'probability' : IDL.Float64,
                'amount' : IDL.Float64,
              }),
              'temperature' : IDL.Opt(IDL.Float64),
              'windSpeed' : IDL.Float64,
              'timestamp' : IDL.Int,
              'windDir' : IDL.Float64,
              'condition' : IDL.Text,
            })
          ),
        }),
      ],
      ['query'],
    ),
  'getWeeklyForecast' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Vec(WeeklyForecast))],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'upsertWeather' : IDL.Func([IDL.Text, WeatherResponse], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DBWeather = IDL.Record({
    'cloudCover' : IDL.Opt(IDL.Float64),
    'temperatureMax' : IDL.Opt(IDL.Float64),
    'temperatureMin' : IDL.Opt(IDL.Float64),
    'country' : IDL.Text,
    'precipitation' : IDL.Opt(IDL.Float64),
    'temperature' : IDL.Opt(IDL.Float64),
    'city' : IDL.Text,
    'windSpeed' : IDL.Opt(IDL.Float64),
    'solar' : IDL.Opt(IDL.Float64),
    'windDirection' : IDL.Opt(IDL.Float64),
    'temperatureDaily' : IDL.Opt(IDL.Float64),
    'precipitationProbability' : IDL.Opt(IDL.Float64),
    'condition' : IDL.Text,
  });
  const Precipitation = IDL.Record({
    'probability' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const WeeklyForecast = IDL.Record({
    'precipitation' : Precipitation,
    'temperature' : IDL.Opt(IDL.Float64),
    'windSpeed' : IDL.Float64,
    'timestamp' : IDL.Int,
    'windDir' : IDL.Float64,
    'condition' : IDL.Text,
  });
  const WeatherResponse = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'daily' : IDL.Record({
      'precipitation' : Precipitation,
      'temperature' : IDL.Opt(IDL.Float64),
      'windSpeed' : IDL.Float64,
      'windDir' : IDL.Float64,
      'condition' : IDL.Text,
    }),
    'weekly' : IDL.Vec(WeeklyForecast),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'conditionForWeather' : IDL.Func([DBWeather], [IDL.Text], ['query']),
    'getBackendCachedRainViewer' : IDL.Func([], [IDL.Text], []),
    'getCachedWeather' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WeatherResponse)],
        ['query'],
      ),
    'getCurrentWeather' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(WeatherResponse)],
        ['query'],
      ),
    'getDailyForecast' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [IDL.Opt(WeeklyForecast)],
        ['query'],
      ),
    'getHealthCheck' : IDL.Func(
        [],
        [
          IDL.Record({
            'status' : IDL.Text,
            'version' : IDL.Text,
            'timestamp' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getRainViewerCache' : IDL.Func([], [IDL.Text], []),
    'getWeather' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(WeatherResponse)],
        ['query'],
      ),
    'getWeatherData' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'country' : IDL.Text,
            'city' : IDL.Text,
            'daily' : IDL.Record({
              'precipitation' : IDL.Record({
                'probability' : IDL.Float64,
                'amount' : IDL.Float64,
              }),
              'temperature' : IDL.Opt(IDL.Float64),
              'windSpeed' : IDL.Float64,
              'windDir' : IDL.Float64,
              'condition' : IDL.Text,
            }),
            'weekly' : IDL.Vec(
              IDL.Record({
                'precipitation' : IDL.Record({
                  'probability' : IDL.Float64,
                  'amount' : IDL.Float64,
                }),
                'temperature' : IDL.Opt(IDL.Float64),
                'windSpeed' : IDL.Float64,
                'timestamp' : IDL.Int,
                'windDir' : IDL.Float64,
                'condition' : IDL.Text,
              })
            ),
          }),
        ],
        ['query'],
      ),
    'getWeeklyForecast' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Vec(WeeklyForecast))],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'upsertWeather' : IDL.Func([IDL.Text, WeatherResponse], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };