/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DBWeather {
  'cloudCover' : [] | [number],
  'temperatureMax' : [] | [number],
  'temperatureMin' : [] | [number],
  'country' : string,
  'precipitation' : [] | [number],
  'temperature' : [] | [number],
  'city' : string,
  'windSpeed' : [] | [number],
  'solar' : [] | [number],
  'windDirection' : [] | [number],
  'temperatureDaily' : [] | [number],
  'precipitationProbability' : [] | [number],
  'condition' : string,
}
export interface Precipitation { 'probability' : number, 'amount' : number }
export interface RainViewerFrames { 'path' : string, 'timestamp' : bigint }
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface WeatherResponse {
  'country' : string,
  'city' : string,
  'daily' : {
    'precipitation' : Precipitation,
    'temperature' : [] | [number],
    'windSpeed' : number,
    'windDir' : number,
    'condition' : string,
  },
  'weekly' : Array<WeeklyForecast>,
}
export interface WeeklyForecast {
  'precipitation' : Precipitation,
  'temperature' : [] | [number],
  'windSpeed' : number,
  'timestamp' : bigint,
  'windDir' : number,
  'condition' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'conditionForWeather' : ActorMethod<[DBWeather], string>,
  'fetchAndCacheRainViewerMetadata' : ActorMethod<
    [],
    {
      'combinedFrames' : Array<RainViewerFrames>,
      'nowcastFrames' : Array<RainViewerFrames>,
      'host' : string,
      'pastFrames' : Array<RainViewerFrames>,
      'timestamp' : Time,
    }
  >,
  'fetchRainViewerTile' : ActorMethod<
    [string],
    [] | [
      {
        'status' : number,
        'body' : string,
        'headers' : Array<[string, string]>,
      }
    ]
  >,
  'getCachedWeather' : ActorMethod<[string], [] | [WeatherResponse]>,
  'getCurrentWeather' : ActorMethod<[string, string], [] | [WeatherResponse]>,
  'getDailyForecast' : ActorMethod<
    [string, string, bigint],
    [] | [WeeklyForecast]
  >,
  'getHealthCheck' : ActorMethod<
    [],
    { 'status' : string, 'version' : string, 'timestamp' : bigint }
  >,
  'getWeather' : ActorMethod<[string, string], [] | [WeatherResponse]>,
  'getWeatherData' : ActorMethod<
    [string, string],
    {
      'country' : string,
      'city' : string,
      'daily' : {
        'precipitation' : { 'probability' : number, 'amount' : number },
        'temperature' : [] | [number],
        'windSpeed' : number,
        'windDir' : number,
        'condition' : string,
      },
      'weekly' : Array<
        {
          'precipitation' : { 'probability' : number, 'amount' : number },
          'temperature' : [] | [number],
          'windSpeed' : number,
          'timestamp' : bigint,
          'windDir' : number,
          'condition' : string,
        }
      >,
    }
  >,
  'getWeeklyForecast' : ActorMethod<
    [string, string],
    [] | [Array<WeeklyForecast>]
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'upsertWeather' : ActorMethod<[string, WeatherResponse], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];